# Generated by Django 4.2.2 on 2023-06-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
